### ISSUE TITLE
Fails on module Install python-pip

### ISSUE THREAD

**Issue by fabianochagas** [atosatto/ansible-dockerswarm#62] opened 2020-01-20 20:29 UTC
Hi, I'm having this error while running my playbook:
TASK [atosatto.docker-swarm : Install python-pip.] ***********************************************************************************************************************************************************
task path: /Users/dev01/.ansible/roles/atosatto.docker-swarm/tasks/main.yml:15
fatal: [worker01]: FAILED! => {
    "msg": "The conditional check '(not skip_docker_py) or (ansible_os_family == 'Debian' and ansible_python_version | version_compare('2.6.0', '>=') and ansible_python_version | version_compare('2.7.9', '<'))' failed. The error was: template error while templating string: no filter named 'version_compare'. String: {% if (not skip_docker_py) or (ansible_os_family == 'Debian' and ansible_python_version | version_compare('2.6.0', '>=') and ansible_python_version | version_compare('2.7.9', '<')) %} True {% else %} False {% endif %}\n\nThe error appears to be in '/Users/fabianochagas/.ansible/roles/atosatto.docker-swarm/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# https://github.com/ansible/ansible-modules-core/issues/1178\n- name: Install python-pip.\n  ^ here\n"
}

I'm using: 
Ansible: 2.9.3
Python: 3.8.1
Role's version: v1.3.2

Thanks cheers!

**Comment by atosatto** [comment] 2020-01-22 21:49
Ehi @fabianochagas, I am afraid your issue might be due to the fact that the 1.x version of the role is using the `version_compare`, that has been deprecated in Ansible 2.9.

Is there any change for you to try with master?
Your issue should have been fixed by https://github.com/atosatto/ansible-dockerswarm/commit/b88591d7e69c562d4e8fba75b35bb7f815f94980.

**Comment by fititnt** [comment] 2020-01-25 09:58
@atosatto same error here with lastest release (`atosatto.docker-swarm (v1.3.2)` and using ansible 2.9.2.

Give me some moment and I will test against the lastest release a fresh install, so you can have some feedback

**Comment by fititnt** [comment] 2020-01-30 17:29
@atosatto I can confirm that master solve this issue. I was using `ansible 2.9.2`.

**Comment by atosatto** [comment] 2020-02-04 09:34
@fabianochagas and @fititnt, I've just released `v2.0.0` of the role which should fix the issue you reported. Please feel free to reopen this ticket in case you this is still not working for you.

**Closed by atosatto** 2020-02-04 09:34 UTC
